# Generated by Django 4.2.30 on 2026-05-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_fix_sku_protect_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='idempotency_key',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
