# Generated by apply_phase_03.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_transaction_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="callback_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
            preserve_default=False,
        ),
    ]
