# Generated by Django 4.2.30 on 2026-05-23 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_province_city_shippingrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['name'], 'verbose_name': 'روش ارسال', 'verbose_name_plural': 'روش\u200cهای ارسال'},
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='base_cost',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='هزینه پایه'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='هزینه هر کیلوگرم اضافی'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='free_above',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='رایگان بالای'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='max_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='حداکثر روز'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='min_days',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='حداقل روز'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(max_length=128, verbose_name='نام روش'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingzone', verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام منطقه'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='provinces',
            field=models.JSONField(verbose_name='لیست استان\u200cها'),
        ),
    ]
