# Generated by Django 4.2 on 2025-01-01 00:00

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_remove_order_idempotency_key_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sms', 'پیامک'), ('email', 'ایمیل'), ('whatsapp', 'واتساپ'), ('push', 'پوش نوتیفیکیشن')], max_length=50, unique=True, verbose_name='نام کانال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کانال اطلاع‌رسانی',
                'verbose_name_plural': 'کانال‌های اطلاع‌رسانی',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('user_registered', 'ثبت‌نام کاربر'), ('order_created', 'ثبت سفارش'), ('order_paid', 'پرداخت سفارش'), ('order_confirmed', 'تایید سفارش'), ('order_processing', 'آماده‌سازی سفارش'), ('order_shipped', 'تحویل به پست/پیک'), ('order_delivered', 'تحویل نهایی'), ('order_cancelled', 'لغو سفارش'), ('payment_failed', 'پرداخت ناموفق')], max_length=30, verbose_name='نوع رویداد')),
                ('recipient', models.CharField(db_index=True, max_length=100, verbose_name='گیرنده')),
                ('rendered_message', models.TextField(verbose_name='متن نهایی')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='موضوع')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شده'), ('failed', 'ناموفق'), ('retrying', 'در حال تلاش مجدد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='داده‌های متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationchannel', verbose_name='کانال')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='store.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ اطلاع‌رسانی',
                'verbose_name_plural': 'لاگ‌های اطلاع‌رسانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_registered', 'ثبت‌نام کاربر'), ('order_created', 'ثبت سفارش'), ('order_paid', 'پرداخت سفارش'), ('order_confirmed', 'تایید سفارش'), ('order_processing', 'آماده‌سازی سفارش'), ('order_shipped', 'تحویل به پست/پیک'), ('order_delivered', 'تحویل نهایی'), ('order_cancelled', 'لغو سفارش'), ('payment_failed', 'پرداخت ناموفق')], max_length=30, verbose_name='نوع رویداد')),
                ('subject', models.CharField(blank=True, default='', help_text='برای ایمیل استفاده می‌شود', max_length=255, verbose_name='موضوع')),
                ('template_text', models.TextField(help_text='از {نام_متغیر} برای متغیرهای داینامیک استفاده کنید', verbose_name='متن قالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationchannel', verbose_name='کانال')),
            ],
            options={
                'verbose_name': 'قالب پیام',
                'verbose_name_plural': 'قالب‌های پیام',
                'ordering': ['event_type', 'channel__name'],
                'unique_together': {('event_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=100, verbose_name='گیرنده')),
                ('context_data', models.JSONField(default=dict, verbose_name='داده‌های متن')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پردازش')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue', to='store.order', verbose_name='سفارش')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='notifications.notificationtemplate', verbose_name='قالب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آیتم صف اطلاع‌رسانی',
                'verbose_name_plural': 'صف اطلاع‌رسانی',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_5c8f71_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_type', 'created_at'], name='notificatio_event_t_7e8e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_3a8f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_2b8a5e_idx'),
        ),
    ]
