# Generated by Django 4.2.30 on 2026-05-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_default_channels'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_status_68c9bc_idx',
            old_name='notificatio_status_5c8f71_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_event_t_988cb5_idx',
            old_name='notificatio_event_t_7e8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_recipie_1f708d_idx',
            old_name='notificatio_recipie_3a8f5e_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationqueue',
            new_name='notificatio_status_b3330d_idx',
            old_name='notificatio_status_2b8a5e_idx',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationtemplate', verbose_name='قالب'),
        ),
    ]
